//  epb_MmBp.h
//  WeChat Embedded Proto Buffer
//
//  Generated by harlliu@tencent.com on 14-11-26.
//  Copyright 2014 Tencent. All rights reserved.
//
// protocol buffer Version : 1.0.4

#ifndef __EPB_MMBP_H__
#define __EPB_MMBP_H__

#include <stdint.h>
#include <stdbool.h>
#include "epb.h"


#define 	timeStampSize							19
#define 	ramdomSize								8
#define 	dataContextSize						32			//remote config user information max size 32bytes
#define 	timerGroupContextSize			127*4
#define 	holidayGroupContextSize		64*12


typedef enum
{
	EEC_system = -1,
	EEC_needAuth = -2,												// 设备未登录 
	EEC_sessionTimeout = -3,									// session 超时，需要重新登录
	EEC_decode = -4,													// proto 解码失败 
	EEC_deviceIsBlock = -5,										// 设备出现异常，导致被微信临时性禁止登录 
	EEC_serviceUnAvalibleInBackground = -6,		// ios 处于后台模式，无法正常服务 
	EEC_deviceProtoVersionNeedUpdate = -7,		// 设备的 proto 版本过老，需要更新 
	EEC_phoneProtoVersionNeedUpdate = -8,			// 微信客户端的 proto版本过老，需要更新 
	EEC_maxReqInQueue = -9,										// 设备发送了多个请求，并且没有收到回包。微信客户端请求队列拥塞。
	EEC_userExitWxAccount = -10								// 用户退出微信帐号。 
} EmErrorCode;


typedef struct
{
	void *none;
} BaseRequest;

typedef struct
{
	int32_t err_code;
	bool has_err_msg;
	CString err_msg;
} BaseResponse;

//======== public    =======
int epb_base_request_pack_size(BaseRequest *request);
int epb_pack_base_request(BaseRequest *request, uint8_t *buf, int buf_len);
BaseRequest *epb_unpack_base_request(BaseRequest *base_request,const uint8_t *buf, int buf_len);
int epb_base_response_pack_size(BaseResponse *response);
int epb_pack_base_response(BaseResponse *response, uint8_t *buf, int buf_len);
BaseResponse *epb_unpack_base_response(BaseResponse *response,const uint8_t *buf, int buf_len);
void epb_unpack_base_response_free(BaseResponse *response);


#endif
